### ISSUE TITLE
Can you test this EFI in USB for me? Thank you

### ISSUE THREAD

**Issue by Baio1977** [dikamsiyoung/Lenovo-Yoga-720-15IKB-EFI-OpenCore-0.8.0#2]
https://drive.google.com/drive/folders/1LE8Awm9TDdpUIsgH2psp9lfXqpkBPLeO?usp=sharing Test this EFI OC 0.8.1 and kext release.
I have deleted some SSDT, if it starts test everything.
If start ioreg ,Disable connection from OS attention for SMBios

**Comment by Baio1977** [comment]
Monterey

**Comment by dikamsiyoung** [comment]
It just booted with extra setup and removal of Wifi and bluetooth kexts.
Going through it now .

**Comment by Baio1977** [comment]
Ioreg please

**Comment by dikamsiyoung** [comment]
[Yoga 720 ioreg.zip](https://github.com/dikamsiyoung/Lenovo-Yoga-720-15IKB-EFI-OpenCore-0.8.0/files/8826448/Yoga.720.ioreg.zip)

**Comment by dikamsiyoung** [comment]
Sleep is broken however

**Comment by Baio1977** [comment]
![Schermata 2022-06-02 alle 20 19 36](https://user-images.githubusercontent.com/59058746/171699481-7770d429-8663-43f8-8104-1afcc0f668a2.png)
I2C1 and I2C2 is good in ioreg , was sleep good before ???
Try everything and tell me where my EFI works worse than yours.

**Comment by dikamsiyoung** [comment]
Yours works better than mine in that you don't use DSDT to activate I2C Touch. Yes my sleep was working before. Lemme try mapping usb

**Comment by dikamsiyoung** [comment]
Also VRAM is 1536MB as opposed to 2048MB on mine

**Comment by Baio1977** [comment]
The nvram is 1536, 2048 is just a useless patch in configplist and I have deleted it.
The sleep also depends on the USB mapping, make sure you get it right by defining the connector type and then pass me the kext USBMap.

https://drive.google.com/drive/folders/1LE8Awm9TDdpUIsgH2psp9lfXqpkBPLeO?usp=sharing test this plese , if start ioreg.

**Comment by dikamsiyoung** [comment]
Can you review the ACPI against mine? I think there are a lot of them that are not needed in yours.

**Comment by dikamsiyoung** [comment]
How did you get 30-bit colour?

**Comment by dikamsiyoung** [comment]
NVM, seems it is for extra display
